name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas

  - pytest
  - pandas
  - numpy
  - sympy
  - requests
  - tabulate
  - sqlite

  - xeus
  - xeus-lua
  - xeus-sqlite
  - xeus-javascript
  #- xeus-cpp
  #- rust

  #- pip:
  #  - jupyter_anywidget_pglite
  #  - anywidget

